//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayersBook.Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlayersBook.Application.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O atributo {0} é obrigatório.
        /// </summary>
        internal static string ATRIBUTO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ATRIBUTO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method: {0} -- Service: {1} -- Ex: {2}.
        /// </summary>
        internal static string ERROR_LOG {
            get {
                return ResourceManager.GetString("ERROR_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao recuperar os dados!.
        /// </summary>
        internal static string FALHA_AO_RECUPERAR_VALORES {
            get {
                return ResourceManager.GetString("FALHA_AO_RECUPERAR_VALORES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao atualizar o registro.
        /// </summary>
        internal static string FALHA_ATUALIZAR_REGISTRO {
            get {
                return ResourceManager.GetString("FALHA_ATUALIZAR_REGISTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao inserir o registro {0} no banco de dados.
        /// </summary>
        internal static string FALHA_INSERIR_REGISTRO {
            get {
                return ResourceManager.GetString("FALHA_INSERIR_REGISTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method: {0} -- Service: {1}.
        /// </summary>
        internal static string INFORMATION_LOG {
            get {
                return ResourceManager.GetString("INFORMATION_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi localizado nenhum registro com essa informação: {0}.
        /// </summary>
        internal static string NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O atributo {0} está com o valor invalido.
        /// </summary>
        internal static string VALOR_INVALIDO {
            get {
                return ResourceManager.GetString("VALOR_INVALIDO", resourceCulture);
            }
        }
    }
}
